name: 'Continuous Integration Pipeline'

on:
  push:
    branches:    
      - 'master' # Push events on master branch
      - 'cboesch' # Push events to branches matching refs/heads/cboesch
      - 'mbouron' # Push events to branches matching refs/heads/mbouron
      - 'releases/*' # Push events to branches matching refs/heads/releases/*
  pull_request: 
    branches:    
      - 'master' # Pull request events on master branch
      - 'cboesch' # Pull request events to branches matching refs/heads/cboesch
      - 'mbouron' # Pull request events to branches matching refs/heads/mbouron
      - 'releases/*' # Pull request events to branches matching refs/heads/releases/*
  schedule:
     - cron:  '0 0 * * *' # Every day at midnight
   
jobs:
  build_libs:

    runs-on: ubuntu-18.04
    container: ubuntu:19.10

    steps:
    - uses: actions/checkout@v1
    - uses: docker://ubuntu:19.10

    - name: Install ubuntu libs
      run: |
        apt-get -y --force-yes update
        apt-get -y install build-essential
        apt-get -y install ffmpeg curl zlib1g-dev  nasm libx264-dev wget pkg-config libglfw3-dev python-pip python2.7-dev python-virtualenv mlocate

    - name: ffmpeg installation
      run: |
        export PREFIX=/usr
        export PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig        
                
        make -j8
        make install        
    - name: Build node.gl
      run: |
        echo $PATH
        make

    - name: Go into the virtualenv and run tests
      run: |
        . /__w/node.gl.ci/node.gl.ci/nodegl-env/bin/activate
        make tests
        echo $?