name: 'tests'

# Trigger the workflow on push or pull request
on: [push, pull_request]

job:
  build_libs:

    runs-on: ubuntu-18.04
    container: ubuntu:19.10

    steps:
    - uses: actions/checkout@v1
    - uses: docker://ubuntu:19.10

    - name: Install dependencies
      run: |
        apt -y --force-yes update
        apt -y install build-essential
        apt -y install curl pkg-config libglfw3-dev python-pip python2.7-dev python-virtualenv
        apt -y install ffmpeg libavcodec-dev libavutil-dev libavformat-dev libavdevice-dev libavfilter-dev libswscale-dev libswresample-dev libpostproc-dev
   
    - name: Build node.gl
      run: |
        make -j$(($(nproc)+1))
    - name: Run tests
      run: |
        make -k -j$(($(nproc)+1)) tests

jobs:
  build_libs:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: |
        brew update
        brew upgrade
        brew install python2 curl pkg-config glfw3 ffmpeg
        sudo easy_install pip
        sudo pip install virtualenv
   
    - name: Build node.gl
      run: |
        make -j$(($(nproc)+1))
