name: 'tests'

on:
  push:
    branches:    
      - 'master' # Push events on master branch
  pull_request: 
    branches:    
      - 'master' # Pull request events on master branch 
   
jobs:
  build_libs:

    runs-on: ubuntu-18.04
    container: ubuntu:19.10

   steps:
    - name: Approve Pull Request
      uses: juliangruber/approve-pull-request-action@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        number: 1

    - uses: actions/checkout@v1
    - uses: docker://ubuntu:19.10

    - name: Install dependencies
      run: |
        apt -y --force-yes update
        apt -y install build-essential
        apt -y install curl pkg-config libglfw3-dev python-pip python2.7-dev python-virtualenv
        apt -y install ffmpeg libavcodec-dev libavutil-dev libavformat-dev libavdevice-dev libavfilter-dev libswscale-dev libswresample-dev libpostproc-dev
   
    - name: Build node.gl
      run: |
        make -j$(nproc)
    - name: Run tests
      run: |
        make -j$(nproc) test
