name: 'Continuous Integration Pipeline'

on:
  push:
    branches:    
      - 'master' # Push events on master branch
      - 'cboesch' # Push events to branches matching refs/heads/cboesch
      - 'mbouron' # Push events to branches matching refs/heads/mbouron
      - 'releases/*' # Push events to branches matching refs/heads/releases/*
  pull_request: 
    branches:    
      - 'master' # Pull request events on master branch
      - 'cboesch' # Pull request events to branches matching refs/heads/cboesch
      - 'mbouron' # Pull request events to branches matching refs/heads/mbouron
      - 'releases/*' # Pull request events to branches matching refs/heads/releases/*
  schedule:
     - cron:  '0 0 * * *' # Every day at midnight
   
jobs:
  build_libs:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install macOS libs
      run: |
        sw_vers
        brew update
        brew upgrade
        brew install python2 curl zlib nasm wget pkg-config glfw3 ffmpeg
        sudo easy_install pip
        sudo pip install virtualenv
   
    - name: Build node.gl
      run: |
        make

    - name: Go into the virtualenv and run tests
      run: |
        . /Users/runner/runners/2.162.0/work/node.gl.ci/node.gl.ci/nodegl-env/bin/activate
        make tests