name: 'Continuous Integration Pipeline'

on:
  push:
    branches:    
      - 'master' # Push events on master branch
      - 'cboesch' # Push events to branches matching refs/heads/cboesch
      - 'mbouron' # Push events to branches matching refs/heads/mbouron
      - 'releases/*' # Push events to branches matching refs/heads/releases/*
  pull_request: 
    branches:    
      - 'master' # Pull request events on master branch
      - 'cboesch' # Pull request events to branches matching refs/heads/cboesch
      - 'mbouron' # Pull request events to branches matching refs/heads/mbouron
      - 'releases/*' # Pull request events to branches matching refs/heads/releases/*
  schedule:
     - cron:  '0 0 * * *' # Every day at midnight
   
jobs:
  build_libs:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install mac libs
      run: |
        brew update
        brew upgrade
        sudo easy_install pip
        brew install python2 curl zlib nasm wget pkg-config glfw3
        sudo pip install virtualenv
        brew install ffmpeg
   
    - name: Build node.gl
      run: |
        echo "MAKE"
        make
 