name: 'Continuous Integration Pipeline'

on:
  push:
    branches:    
      - 'master' # Push events on master branch
  pull_request: 
    branches:    
      - 'master' # Pull request events on master branch
   
jobs:
  build_libs:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: |
        brew update
        brew upgrade
        brew install python2 curl wget pkg-config glfw3 ffmpeg
        sudo easy_install pip
        sudo pip install virtualenv
   
    - name: Build node.gl
      run: |
        make
 
