name: 'tests Mac'

on:
  push:
    branches:    
      - 'master' # Push events on master branch
  pull_request:

jobs:
  build_libs:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: |
        brew update
        brew upgrade
        brew install python2 pkg-config ffmpeg
        sudo easy_install pip
        sudo pip install virtualenv
   
    - name: Build node.gl
      run: |
        make -j$(($(sysctl -n hw.logicalcpu)+1))
 
